[package]
name = "bufferedlinear_tools"
version = "2.0.0"
edition = "2025"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rayon = "1.10"
thiserror = "2.0.3"
zstd = "0.13"
twox-hash = "1.1.2"
chrono = "0.4"
